


export const navConstants = {
   HOME : "HOME",
   ANALYTICS : "ANALYTICS",
   RECORD: "RECORD",
}

export const EntryConst = {
   MISCELLANEOUSEXPENSES:"MISCELLANEOUS EXPENSES",
   MISCELLANEOUSINCOME:"MISCELLANEOUS INCOME",
   FIXEDEXPENSES:"FIXED EXPENSES",
   FIXEDINCOME:"FIXED INCOME",
}